openapi: 3.1.1
info:
  title: Tinyval
  description: |
    Hash table service for storing and retrieving binary blobs using their SHA-256 hashes as keys.
  version: 0.1.0
paths:
  /blobs/{hash}:
    get:
      tags:
        - Storage
      summary: Get blob
      parameters:
        - $ref: "#/components/parameters/hashPathParam"
      responses:
        "200":
          description: Successful Response
          content:
            application/octet-stream: {}
        "400":
          description: Bad Request
        "404":
          description: Not Found
    put:
      tags:
        - Storage
      summary: Put blob
      parameters:
        - $ref: "#/components/parameters/hashPathParam"
      requestBody:
        content:
          application/octet-stream:
            schema:
              type: string
              format: binary
        required: true
      responses:
        "200":
          description: Successful Response
        "400":
          description: Bad Request
        "422":
          description: Unprocessable Entity
    head:
      tags:
        - Storage
      summary: Check if blob exists
      parameters:
        - $ref: "#/components/parameters/hashPathParam"
      responses:
        "200":
          description: Successful Response
        "400":
          description: Bad Request
        "404":
          description: Not Found
components:
  parameters:
    hashPathParam:
      name: hash
      in: path
      required: true
      description: SHA-256 hash
      example: 38bf13ef9985026a3fb71fea9ae95826cf8d84b02f300d481ba90a61f35504a6
      schema:
        pattern: ^[0-9a-f]{64}$
        type: string
        description: SHA-256 hash
